package com.lewatihari.enums;

public enum ResponseEnum {
    SUCCESS,
    ERROR,
    ACCOUNT_NOT_FOUND,
    EMAIL_ALREADY_EXIST,
    SIGN_IN_FAILED,
    CATEGORY_ALREADY_EXIST,
    CATEGORY_NOT_FOUND,
    MERCHANT_ALREADY_EXIST, FACILITY_NOT_FOUND,
}
